---
dependencies:
  - name: egvimo.installer
    src: git+https://github.com/egvimo/ansible-role-installer.git
    version: main
collections:
  - name: https://github.com/egvimo/ansible-collection-misc.git
    type: git
    version: main
