---
- hosts: workstations
  tasks:
    - import_role:
        name: egvimo.misc.installer
      vars:
        installer_packages:
          - corretto11
          - dbeaver
          - docker
          - git
          - kubectl
          - nvm
          - starship
          - vagrant
          - vscode
          - windows-terminal
