---
- hosts: workstations
  tasks:
    - name: Import installer role
      ansible.builtin.import_role:
        name: egvimo.misc.installer
      vars:
        installer_packages:
          - 7zip
          - dbeaver
          - greenshot
          - helm
          - k9s
          - kubectl
          - licecap
          - mremoteng
          - notepadplusplus
          - nvm
          - starship
          - vscode
          - windows-terminal
          - winmerge
          - winscp

    - name: Import Docker WSL role
      ansible.builtin.import_role:
        name: egvimo.misc.docker_wsl
