---
- hosts: workstations
  tasks:
    - import_role:
        name: egvimo.installer
      vars:
        installer_packages:
          - corretto11
          - dbeaver
          - kubectl
          - nvm
          - starship
          - vscode
          - windows-terminal
