---
- hosts: wsl
  tasks:
    - name: Allow WSL user to have passwordless sudo
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ lookup('env','USER') }}"
        state: present
        regexp: "^{{ lookup('env','USER') }} ALL="
        line: "{{ lookup('env','USER') }} ALL=(ALL) NOPASSWD: ALL"
        create: true
        validate: /usr/sbin/visudo -cf %s
      become: true

    - name: Import installer role
      ansible.builtin.import_role:
        name: egvimo.misc.installer
      vars:
        installer_packages:
          - starship

    - name: Import Docker WSL role
      ansible.builtin.import_role:
        name: egvimo.misc.docker_wsl
