name: Ansible Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_FORCE_COLOR: 1

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Kerberos dependencies
        run: sudo apt install python3-dev libkrb5-dev krb5-user

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run Ansible lint
        run: ansible-lint workstations.yml
