name: Ansible Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    env:
      ANSIBLE_FORCE_COLOR: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          submodules: recursive

      - name: Set up Python 3
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install packages
        run: sudo apt install python3-dev libkrb5-dev krb5-user

      - name: Install pipenv
        run: pip3 install pipenv

      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run Ansible lint
        run: pipenv run ansible-lint workstations.yml
